### ISSUE TITLE
compile failing

### ISSUE THREAD

**Issue by der0pa** [omnia-network/ic-websocket-gateway#3]
rustc stable, nightly, code-spaces all fail on M1 macOS

console:

douglassmith@static-76-161-87-250 ic-websocket-gateway % cargo run
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/ic_websocket_gateway`
Tracing to file: ./data/traces/gateway_1696422955710.log
  2023-10-04T12:35:55.729796Z  INFO ic_websocket_gateway: Deployment info: DeploymentInfo { subnet_url: "http://127.0.0.1:4943", gateway_address: "0.0.0.0:8080", polling_interval: 100, send_status_interval: 30000, tls_certificate_pem_path: None, tls_certificate_key_pem_path: None }
    at src/ic-websocket-gateway/src/main.rs:93

thread 'main' panicked at 'could not get new agent: TransportError(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(4943), path: "/api/v2/status", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) })', src/ic-websocket-gateway/src/gateway_server.rs:97:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
douglassmith@static-76-161-87-250 ic-websocket-gateway %

**Comment by Luca8991** [comment]
The compilation of the code went fine on your side, since you are getting these log messages:
```bash
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running target/debug/ic_websocket_gateway
Tracing to file: ./data/traces/gateway_1696422955710.log
2023-10-04T12:35:55.729796Z INFO ic_websocket_gateway: Deployment info: DeploymentInfo { subnet_url: "http://127.0.0.1:4943/", gateway_address: "0.0.0.0:8080", polling_interval: 100, send_status_interval: 30000, tls_certificate_pem_path: None, tls_certificate_key_pem_path: None }
at src/ic-websocket-gateway/src/main.rs:93
```

As you can see from the log, in the deployment info the `subnet_url` is configured to `http://127.0.0.1:4943/` (which is the default). This means that the gateway will poll canisters on the [local replica](https://internetcomputer.org/docs/current/references/cli-reference/dfx-start). When the gateway starts, it attempts to fetch the root key from the replica if the `subnet_url` is different than the IC mainnet URL (https://icp0.io).

The error you're getting means that the underlying [Rust agent](https://docs.rs/ic-agent/latest/ic_agent/) is not able to fetch the root key from the local replica, which likely means that the local replica is not running.

To change the `subnet_url` to, for example, the IC mainnet, run the gateway with:
```
cargo run --subnet-url https://icp0.io
```
More about the configuration parameters available can be found in the [README](https://github.com/omnia-network/ic-websocket-gateway#options-available).

**Comment by Luca8991** [comment]
@der0pa did this solve your issue?

**Comment by der0pa** [comment]
was really just following your readme to learn about WS on IC.  so no.

**Comment by Luca8991** [comment]
@der0pa we now have a Docker image on Docker Hub, published at [omniadevs/ic-websocket-gateway](https://hub.docker.com/r/omniadevs/ic-websocket-gateway) repo, which may help you.
In the meantime, I'm closing this issue due to inactivity. Feel free to reopen it or open a new one if you still encounter some issues.
